#!/usr/bin/env python3
"""
render_mcp.py — Fan-out MCP configurations from hub/mcp-servers.json to all targets.
"""

import json
import sys
import pathlib
import os
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
CANONICAL = ROOT / "hub" / "mcp-servers.json"
ENV_LOCAL = ROOT / ".env.local"

TARGETS = {
    "claude": ROOT / ".mcp.json",
    "cursor": ROOT / ".cursor" / "mcp.json",
    "codex": ROOT / ".codex" / "config.toml",
}

MODE = "fix"
TARGET_CLI = None
DRIFT = False

def load_env(path: pathlib.Path) -> dict:
    env = {}
    if path.exists():
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#"): continue
            if "=" in line:
                key, val = line.split("=", 1)
                env[key.strip()] = val.strip()
    return env

def substitute_env(data, env_vars: dict):
    if isinstance(data, dict):
        return {k: substitute_env(v, env_vars) for k, v in data.items()}
    elif isinstance(data, list):
        return [substitute_env(i, env_vars) for i in data]
    elif isinstance(data, str):
        def replacer(match):
            var_name = match.group(1)
            val = os.environ.get(var_name) or env_vars.get(var_name)
            if val is None:
                print(f"ERROR: Missing environment variable '${var_name}' in .env.local or shell environment.")
                sys.exit(1)
            return val
        return re.sub(r"\${(\w+)}", replacer, data)
    return data

def _display_path(path: pathlib.Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def compare_or_write(target: pathlib.Path, content: str):
    global DRIFT
    target.parent.mkdir(parents=True, exist_ok=True)
    if MODE == "check":
        if not target.exists() or target.read_text(encoding="utf-8") != content:
            print(f"DRIFT: {_display_path(target)}")
            DRIFT = True
    else:
        target.write_text(content, encoding="utf-8")
        print(f"wrote: {_display_path(target)}")

def read_json(path: pathlib.Path) -> dict:
    if path.exists():
        with path.open(encoding="utf-8") as f:
            try:
                return json.load(f)
            except json.JSONDecodeError:
                return {}
    return {}

def strip_meta(data):
    """Recursively strip unicli-hub meta keys (_comment, _overrides, _targets, etc.)."""
    if isinstance(data, dict):
        return {k: strip_meta(v) for k, v in data.items() if not k.startswith("_")}
    elif isinstance(data, list):
        return [strip_meta(i) for i in data]
    return data

# Keep strip_comments as an alias for backwards compatibility
strip_comments = strip_meta


def apply_overrides(server: dict, cli: str) -> dict:
    """Merge target-specific _overrides into server config."""
    overrides = server.get("_overrides", {})
    if cli not in overrides:
        return server
    import copy
    merged = copy.deepcopy(server)
    merged.update(overrides[cli])
    return merged


def filter_servers(raw_servers: dict, cli: str) -> dict:
    """Filter servers by _targets (if specified) and apply _overrides."""
    result = {}
    for name, cfg in raw_servers.items():
        targets = cfg.get("_targets")
        if targets is not None and cli not in targets:
            continue  # excluded from this CLI
        result[name] = apply_overrides(cfg, cli)
    return result


def toml_string(value: str) -> str:
    """Render a basic TOML string via JSON escaping, which is TOML-compatible."""
    return json.dumps(value, ensure_ascii=False)


def toml_array(values: list) -> str:
    return "[" + ", ".join(toml_string(str(v)) for v in values) + "]"


def render_codex_toml(servers: dict) -> str:
    lines = [
        "# MCP servers - generated by render_mcp.py, do not edit directly",
        "",
    ]

    for name, cfg in servers.items():
        clean = strip_meta(cfg)
        lines.append(f"[mcp_servers.{name}]")

        if clean.get("type") == "http":
            url = clean.get("url") or clean.get("httpUrl") or clean.get("serverUrl")
            if url:
                lines.append(f"url = {toml_string(str(url))}")
            token_env = clean.get("bearer_token_env_var") or clean.get("bearerTokenEnvVar")
            if token_env:
                lines.append(f"bearer_token_env_var = {toml_string(str(token_env))}")
        else:
            if "command" in clean:
                lines.append(f"command = {toml_string(str(clean['command']))}")
            if "args" in clean:
                lines.append(f"args = {toml_array(clean['args'])}")

        env = clean.get("env") or {}
        if env:
            lines.append(f"[mcp_servers.{name}.env]")
            for key, value in env.items():
                lines.append(f"{key} = {toml_string(str(value))}")

        lines.append("")

    return "\n".join(lines).rstrip() + "\n"

def main():
    global MODE, DRIFT, TARGET_CLI
    for arg in sys.argv[1:]:
        if arg in ["--fix", "--check"]: 
            MODE = arg[2:]
        elif arg.startswith("--target="):
            TARGET_CLI = arg.split("=")[1]

    if not CANONICAL.exists():
        print(f"ERROR: {CANONICAL} not found")
        sys.exit(1)

    env_vars = load_env(ENV_LOCAL)
    src = read_json(CANONICAL)
    raw_servers = src.get("mcpServers", {})
    
    # Substitute env variables (before per-CLI filtering so overrides can also ref env vars)
    raw_servers_subst = substitute_env(raw_servers, env_vars)

    # 1. Claude (Pure JSON — default args, no overrides)
    if TARGET_CLI in [None, "claude"]:
        cli_servers = filter_servers(raw_servers_subst, "claude")
        clean = strip_meta(cli_servers)
        compare_or_write(TARGETS["claude"], json.dumps({"mcpServers": clean}, indent=2, ensure_ascii=False) + "\n")

    # 2. Cursor (Pure JSON — ide-assistant context)
    if TARGET_CLI in [None, "cursor"]:
        cli_servers = filter_servers(raw_servers_subst, "cursor")
        clean = strip_meta(cli_servers)
        compare_or_write(TARGETS["cursor"], json.dumps({"mcpServers": clean}, indent=2, ensure_ascii=False) + "\n")

    # 4. Antigravity (mcp_config.json — ide-assistant context)
    if TARGET_CLI in [None, "antigravity"]:
        cli_servers = filter_servers(raw_servers_subst, "antigravity")
        ag_servers = {}
        for name, cfg in cli_servers.items():
            ag_cfg = dict(cfg)
            t = ag_cfg.pop("type", None)
            if t == "http":
                ag_cfg["serverUrl"] = ag_cfg.pop("url", ag_cfg.pop("httpUrl", ""))
            ag_servers[name] = ag_cfg
        clean = strip_meta(ag_servers)
        compare_or_write(ROOT / ".agents" / "mcp_config.json", json.dumps({"mcpServers": clean}, indent=2, ensure_ascii=False) + "\n")

    # 5. Codex (TOML — project-local config)
    if TARGET_CLI in [None, "codex"]:
        cli_servers = filter_servers(raw_servers_subst, "codex")
        compare_or_write(TARGETS["codex"], render_codex_toml(cli_servers))

    if MODE == "check" and DRIFT:
        sys.exit(1)

if __name__ == "__main__":
    main()
