#!/usr/bin/env python3
"""generated_file_guard.py — PreToolUse hook.

Blocks direct edits to files that are auto-generated by sync.sh.
Reads the tool invocation JSON from stdin, inspects the target path,
and exits with code 1 (fail-closed) if the agent is trying to write to
a derived file. The error message points at the canonical source the
agent should edit instead.

Schema support:
  - Claude Code: {"tool_input": {"file_path": "..."}}
  - Cursor:      {"toolInput": {"file_path": "..."}}
  - Gemini CLI:  {"tool_input": {"path": "..."}} / substituted via {{args}}
  - Kiro:        {"args": {"file_path": "..."}}
"""

from __future__ import annotations

import json
import pathlib
import sys
from fnmatch import fnmatch

RULES_ROOT = pathlib.Path(__file__).resolve().parent.parent


def resolve_cursor_skill_hint(rel: str) -> str:
    """Map .cursor/skills/<name>/SKILL.md edits back to canonical agents/ or skills/."""
    parts = rel.split("/")
    if len(parts) < 3:
        return "hub/skills/ (invalid path)"
    skill = parts[-2]
    agents_md = RULES_ROOT / "agents" / f"{skill}.md"
    if agents_md.is_file():
        return (
            f"hub/agents/{skill}.md "
            f"(sync mirrors body to .cursor/skills/{skill}/SKILL.md)"
        )
    folder_skill = RULES_ROOT / "skills" / skill / "SKILL.md"
    if folder_skill.is_file():
        return f"hub/skills/{skill}/"
    flat_skill = RULES_ROOT / "skills" / f"{skill}.md"
    if flat_skill.is_file():
        return f"hub/skills/{skill}.md"
    return f"hub/skills/ (no canonical match for `{skill}`)"



# (exact path, hint describing where to edit instead)
EXACT_GUARDS: list[tuple[str, str]] = [
    ("CLAUDE.md",
     ".unicli-hub/templates/CLAUDE.md.tmpl + hub/{project-context,memory}/*.md"),
    ("AGENTS.md",
     ".unicli-hub/templates/AGENTS.md.tmpl + hub/{project-context,core-workflow,memory}/*.md"),
    ("GEMINI.md",
     ".unicli-hub/templates/GEMINI.md.tmpl + hub/{project-context,core-workflow}.md"),
    ("AGY.md",
     ".unicli-hub/templates/AGY.md.tmpl + hub/{project-context,core-workflow}.md"),
    (".cursor/rules/workflow.mdc",
     ".unicli-hub/templates/cursor-workflow-slim.md + hub/memory/*.md (regenerate: sync.sh)"),
    (".cursor/rules/project-context.mdc", "hub/project-context.md"),
    (".cursor/rules/memory.mdc", "hub/memory/*.md"),
    # Claude Code project hooks config
    (".claude/settings.json", "hub/claude-hooks.json (regenerate: sync.sh)"),
    # MCP config files
    (".mcp.json", "hub/mcp-servers.json"),
    (".cursor/mcp.json", "hub/mcp-servers.json"),
    (".kiro/settings/mcp.json", "hub/mcp-servers.json"),
    (".gemini/settings.json", "hub/mcp-servers.json"),
    (".agy/settings.json", "hub/mcp-servers.json"),
    (".codex/config.toml", "hub/mcp-servers.json"),
]

# (glob pattern, hint template; placeholders: {name}, {skill}, {source})
GLOB_GUARDS: list[tuple[str, str]] = [
    (".claude/agents/*.md",  "hub/agents/{name}"),
    (".cursor/agents/*.md",  "hub/agents/{name}"),
    (".gemini/agents/*.md",  "hub/agents/{name}"),
    (".agy/agents/*.md",     "hub/agents/{name}"),
    (".codex/prompts/*.md",  "hub/agents/{name}"),
    (".kiro/steering/*.md",  "hub/steering/{name}"),
    (".gemini/skills/*/SKILL.md", "hub/skills/{skill}.md"),
    (".agy/skills/*/SKILL.md",    "hub/skills/{skill}.md"),
    (".cursor/skills/*/SKILL.md", "__cursor_skill_hint__"),
    (".kiro/agents/prompts/*",    "hub/agents/"),
]

STEERING_MAP = {
    "01-project-context.md": "project-context.md",
    "02-core-workflow.md": "core-workflow.md",
    "03-memory.md": "memory/*.md",
}


def extract_path(payload: dict) -> str:
    def dig(d: dict, *keys: str) -> str:
        node = d
        for k in keys:
            if not isinstance(node, dict):
                return ""
            node = node.get(k, "")
        return node if isinstance(node, str) else ""

    for keys in (
        ("tool_input", "file_path"),
        ("tool_input", "path"),
        ("toolInput", "file_path"),
        ("toolInput", "path"),
        ("args", "file_path"),
        ("args", "path"),
    ):
        val = dig(payload, *keys)
        if val:
            return val
    return ""


def normalize(path: str) -> str:
    if not path:
        return ""
    marker = "/unicli-hub/"
    if marker in path:
        path = path.split(marker, 1)[1]
    return path.lstrip("/")


def resolve_hint(pattern: str, rel: str, template: str) -> str:
    if pattern == ".cursor/skills/*/SKILL.md" and template == "__cursor_skill_hint__":
        return resolve_cursor_skill_hint(rel)
    parts = rel.split("/")
    name = parts[-1]
    if "{skill}" in template:
        skill = parts[-2] if len(parts) >= 2 else "<name>"
        return template.replace("{skill}", skill)
    if "{source}" in template and pattern.startswith(".kiro/steering/"):
        return template.replace("{source}", STEERING_MAP.get(name, ""))
    return template.replace("{name}", name)


def block(rel: str, hint: str) -> int:
    reason = (
        f"Generated file block: direct edit of `{rel}` is not allowed. "
        f"Edit the canonical source instead: {hint}. "
        "Then run `./sync.sh --fix`."
    )
    print(reason, file=sys.stderr)
    print(
        json.dumps(
            {
                "permission": "deny",
                "user_message": reason,
                "agent_message": reason,
                "hookSpecificOutput": {
                    "hookType": "PreToolUse",
                    "permissionDecision": "block",
                    "permissionDecisionReason": reason,
                },
            }
        )
    )
    return 1


def main() -> int:
    raw = sys.stdin.read()
    if not raw.strip():
        return 0
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError:
        return 0

    target = extract_path(payload)
    rel = normalize(target)
    if not rel:
        return 0

    for exact, hint in EXACT_GUARDS:
        if rel == exact:
            return block(rel, hint)

    for pattern, hint_tmpl in GLOB_GUARDS:
        if fnmatch(rel, pattern):
            return block(rel, resolve_hint(pattern, rel, hint_tmpl))

    return 0


if __name__ == "__main__":
    sys.exit(main())
