#!/usr/bin/env python3
"""
pre_tool_use.py — Guards derived CLI directories from direct edits.

Direct edits to .claude/, .cursor/, .gemini/, .agents/, .kiro/, .codex/
are blocked. Edit hub/ instead and let sync.sh fanout the changes.

Per-CLI event names that map to this hook:
  Claude Code : PreToolUse    (.claude/settings.json  → hooks.PreToolUse)
  Cursor      : preToolUse    (.cursor/hooks.json     → hooks.preToolUse)
  Gemini CLI  : BeforeTool    (.gemini/settings.json  → hooks.BeforeTool)
  Antigravity : (no hook system as of 2026-05)

Stdin : JSON event payload.
  tool_name  : str   — e.g. "Edit", "Write", "Bash"
  tool_input : dict  — tool arguments (file_path for Edit/Write)
  session_id : str

Stdout: JSON {"permission":"allow"|"deny", "reason"?:str}.
Exit 0 = allow.
"""

import json
import pathlib
import sys

# Derived directories that must not be directly edited — edit hub/ instead
GUARD_DIRS = [
    ".claude/",
    ".cursor/",
    ".gemini/",
    ".agents/",
    ".kiro/",
    ".codex/",
    ".antigravitycli/",
]

# Derived files at repo root (sync.sh generates these)
GUARD_ROOT_FILES = [
    "CLAUDE.md",
    "AGENTS.md",
    "GEMINI.md",
]

# Files inside guarded dirs that ARE allowed to be edited directly
# (e.g. user-local settings that are not fanned out)
ALLOWLIST = [
    ".claude/settings.local.json",
    ".claude/CLAUDE.md",  # project-level override, not fanout
]

SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent  # hub/hooks/ → hub/ → repo root


def main() -> None:
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        payload = {}

    tool_name = payload.get("tool_name", "")
    if tool_name not in ("Edit", "Write"):
        print(json.dumps({"permission": "allow"}))
        return

    file_path = payload.get("tool_input", {}).get("file_path", "")
    if not file_path:
        print(json.dumps({"permission": "allow"}))
        return

    # Normalize to relative path from repo root
    try:
        rel = str(pathlib.Path(file_path).resolve().relative_to(REPO_ROOT))
    except ValueError:
        # Outside repo — not our concern
        print(json.dumps({"permission": "allow"}))
        return

    # Check allowlist first
    if any(rel == a or rel.startswith(a.rstrip("/") + "/") for a in ALLOWLIST):
        print(json.dumps({"permission": "allow"}))
        return

    # Block guarded root files
    if rel in GUARD_ROOT_FILES:
        print(json.dumps({
            "permission": "deny",
            "reason": (
                f"'{rel}' is a derived file generated by sync.sh. "
                "Edit the canonical source in hub/ and run './sync.sh --fix' instead."
            )
        }))
        return

    # Block guarded directories
    for guard in GUARD_DIRS:
        if rel.startswith(guard):
            print(json.dumps({
                "permission": "deny",
                "reason": (
                    f"'{rel}' is inside a derived directory ('{guard}'). "
                    "Edit the canonical source in hub/ and let sync.sh fanout the changes."
                )
            }))
            return

    print(json.dumps({"permission": "allow"}))


if __name__ == "__main__":
    main()
