#!/usr/bin/env python3
"""generated_file_guard.py — PreToolUse hook.

Blocks direct edits to files that are auto-generated by sync.sh.
Reads the tool invocation JSON from stdin, inspects the target path,
and exits with code 1 (fail-closed) if the agent is trying to write to
a derived file. The error message points at the canonical source the
agent should edit instead.

Schema support:
  - Claude Code: {"tool_input": {"file_path": "..."}}
  - Cursor:      {"toolInput": {"file_path": "..."}}
  - Gemini CLI:  {"tool_input": {"path": "..."}} / substituted via {{args}}
  - Kiro:        {"args": {"file_path": "..."}}
"""

from __future__ import annotations

import json
import sys
from fnmatch import fnmatch


# (exact path, hint describing where to edit instead)
EXACT_GUARDS: list[tuple[str, str]] = [
    ("CLAUDE.md",
     ".unicli-rules/templates/CLAUDE.md.tmpl + .unicli-rules/{project-context,core-workflow}.md"),
    ("AGENTS.md",
     ".unicli-rules/templates/AGENTS.md.tmpl + .unicli-rules/{project-context,core-workflow,memory}/*.md"),
    (".gemini/GEMINI.md",
     ".unicli-rules/templates/GEMINI.md.tmpl + .unicli-rules/{project-context,core-workflow}.md"),
    (".cursor/rules/workflow.mdc", ".unicli-rules/core-workflow.md"),
    (".cursor/rules/project-context.mdc", ".unicli-rules/project-context.md"),
    (".cursor/rules/memory.mdc", ".unicli-rules/memory/*.md"),
    # MCP config files — generated by render_mcp.py via sync.sh
    (".mcp.json", ".unicli-rules/common/mcp-servers.json"),
    (".cursor/mcp.json", ".unicli-rules/common/mcp-servers.json"),
    (".kiro/mcp.json", ".unicli-rules/common/mcp-servers.json"),
    (".gemini/settings.json", ".unicli-rules/common/mcp-servers.json (mcpServers block)"),
    (".codex/config.toml", ".unicli-rules/common/mcp-servers.json (mcpServers block)"),
]

# (glob pattern, hint template; placeholders: {name}, {skill}, {source})
GLOB_GUARDS: list[tuple[str, str]] = [
    (".claude/agents/*.md",  ".unicli-rules/agents/{name}"),
    (".cursor/agents/*.md",  ".unicli-rules/agents/{name}"),
    (".gemini/agents/*.md",  ".unicli-rules/agents/{name}"),
    (".codex/prompts/*.md",  ".unicli-rules/agents/{name}"),
    (".kiro/steering/*.md",  ".unicli-rules/{source}"),
    (".gemini/skills/*/SKILL.md", ".unicli-rules/skills/{skill}.md"),
    (".cursor/skills/*/SKILL.md", ".unicli-rules/skills/{skill}.md"),
    (".kiro/agents/prompts/*",    ".unicli-rules/agents/ (this path is a symlink; edit the canonical file)"),
]

STEERING_MAP = {
    "01-project-context.md": "project-context.md",
    "02-core-workflow.md": "core-workflow.md",
    "03-memory.md": "memory/*.md",
}


def extract_path(payload: dict) -> str:
    def dig(d: dict, *keys: str) -> str:
        node = d
        for k in keys:
            if not isinstance(node, dict):
                return ""
            node = node.get(k, "")
        return node if isinstance(node, str) else ""

    for keys in (
        ("tool_input", "file_path"),
        ("tool_input", "path"),
        ("toolInput", "file_path"),
        ("toolInput", "path"),
        ("args", "file_path"),
        ("args", "path"),
    ):
        val = dig(payload, *keys)
        if val:
            return val
    return ""


def normalize(path: str) -> str:
    if not path:
        return ""
    marker = "/unicli-hub/"
    if marker in path:
        path = path.split(marker, 1)[1]
    return path.lstrip("/")


def resolve_hint(pattern: str, rel: str, template: str) -> str:
    parts = rel.split("/")
    name = parts[-1]
    if "{skill}" in template:
        skill = parts[-2] if len(parts) >= 2 else "<name>"
        return template.replace("{skill}", skill)
    if "{source}" in template and pattern.startswith(".kiro/steering/"):
        return template.replace("{source}", STEERING_MAP.get(name, ""))
    return template.replace("{name}", name)


def block(rel: str, hint: str) -> int:
    print(
        f"[generated-file-guard] BLOCKED: direct edit of generated file '{rel}'.\n"
        f"Edit the canonical source instead: {hint}\n"
        f"Then run: ./.unicli-rules/sync.sh --fix",
        file=sys.stderr,
    )
    return 1


def main() -> int:
    raw = sys.stdin.read()
    if not raw.strip():
        return 0
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError:
        return 0

    target = extract_path(payload)
    rel = normalize(target)
    if not rel:
        return 0

    for exact, hint in EXACT_GUARDS:
        if rel == exact:
            return block(rel, hint)

    for pattern, hint_tmpl in GLOB_GUARDS:
        if fnmatch(rel, pattern):
            return block(rel, resolve_hint(pattern, rel, hint_tmpl))

    return 0


if __name__ == "__main__":
    sys.exit(main())
